package commands

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/cidx-org/cidx/v3/pkg/presets"
	"github.com/urfave/cli/v2"
)

const defaultCatalogueReferenceFile = "docs/reference/catalogue.md"

var cataloguePhaseOrder = map[string]int{
	"security": 0, "code": 1, "test": 2, "build": 3, "docker": 4, "release": 5,
}

// RenderCatalogueReference renders the committed page from the built-in
// catalogue. With no generated timestamp, equal inputs produce equal bytes.
func RenderCatalogueReference() (string, error) {
	catalogue, err := presets.Catalogue()
	if err != nil {
		return "", fmt.Errorf("loading the catalogue: %w", err)
	}

	names := make([]string, 0, len(catalogue))
	for name := range catalogue {
		names = append(names, name)
	}
	sort.Slice(names, func(i, j int) bool {
		pi, pj := catalogue[names[i]].Phase, catalogue[names[j]].Phase
		if pi != pj {
			oi, iKnown := cataloguePhaseOrder[pi]
			oj, jKnown := cataloguePhaseOrder[pj]
			switch {
			case iKnown && jKnown:
				return oi < oj
			case iKnown != jKnown:
				return iKnown
			default:
				return pi < pj
			}
		}
		return names[i] < names[j]
	})

	var sb strings.Builder
	sb.WriteString(`# Preset Catalogue

Every preset the built-in catalogue ships: the image it runs, pinned by
digest, what its declarations imply, and which update policy governs it.

This page is generated by ` + "`cidx preset catalogue`" + ` from
` + "`pkg/presets/presets.toml`" + ` and committed; a test regenerates it, so a
preset added or repinned without regenerating the page fails the build. The
**Notes** column is the preset's own description — the one human-written field.

**Capabilities** are derived from the declared env and volumes, never from the
command: ` + "`publishing-credential`" + ` (a secret is handed to the container)
and ` + "`docker-socket`" + ` (the host's Docker socket is mounted). They are
the mechanical half of the context the vulnerability decisions in
` + "`known-vulnerabilities.toml`" + ` are reviewed against.

**Update policy** follows from the registry: a registry that dates its tags
feeds rule 2's cooldown and the monitor promotes from it (**automatic**); one
that does not — dhi.io, ghcr.io — can never clear the cooldown, so every move
is a reviewed **manual repin** ([image lifecycle](../core-concepts/image-lifecycle.md)).

| Preset | Phase | Image | Hardened | Capabilities | Update policy | Notes |
| --- | --- | --- | --- | --- | --- | --- |
`)

	for _, name := range names {
		p := catalogue[name]
		image := p.Image
		if at := strings.Index(image, "@"); at >= 0 {
			image = image[:at]
		}
		hardened := ""
		if p.Hardened {
			hardened = "yes"
		}
		caps := strings.Join(presets.Capabilities(p), ", ")
		policy := "automatic"
		if !registryDatesTags(p.Image) {
			policy = "manual repin"
		}
		fmt.Fprintf(&sb, "| `%s` | %s | `%s` | %s | %s | %s | %s |\n",
			name, p.Phase, image, hardened, caps, policy, referenceCell(p.Description))
	}

	sb.WriteString(`
Digests are elided above for readability; the pins themselves live in
` + "`pkg/presets/presets.toml`" + `, and ` + "`cidx preset info <name>`" + `
prints any preset in full, digest included.
`)
	return sb.String(), nil
}

// referenceCell keeps a description on one table row.
func referenceCell(s string) string {
	s = strings.NewReplacer("\n", " ", "|", "\\|").Replace(s)
	if s == "" {
		return "—"
	}
	return s
}

func presetCatalogueCommand() *cli.Command {
	return &cli.Command{
		Name:  "catalogue",
		Usage: "Write the committed catalogue reference page",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:    "output",
				Aliases: []string{"o"},
				Value:   defaultCatalogueReferenceFile,
				Usage:   "Path to write the page to ('-' for stdout)",
			},
		},
		Action: func(c *cli.Context) error {
			page, err := RenderCatalogueReference()
			if err != nil {
				return err
			}
			out := c.String("output")
			if out == "-" {
				fmt.Print(page)
				return nil
			}
			if err := os.WriteFile(out, []byte(page), 0644); err != nil {
				return fmt.Errorf("failed to write %s: %w", out, err)
			}
			fmt.Printf("Wrote %s: %d preset(s).\n", out, strings.Count(page, "\n| `"))
			return nil
		},
	}
}
