package generate

import (
	"strings"
	"testing"

	"github.com/cidx-org/cidx/pkg/config"
)

func TestGitHub_NoPipelines(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{},
	}

	_, err := GitHub(cfg)
	if err == nil {
		t.Error("expected error for empty pipelines")
	}
	if !strings.Contains(err.Error(), "no pipelines") {
		t.Errorf("expected 'no pipelines' error, got: %v", err)
	}
}

func TestGitHub_BasicCI(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"ci": {Phases: []string{"security", "code", "test"}},
		},
	}

	output, err := GitHub(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Check structure
	checks := []struct {
		name     string
		expected string
	}{
		{"header", "Generated by cidx"},
		{"name", "name: CIDX CI"},
		{"push trigger", "push:"},
		{"bootstrap job", "bootstrap:"},
		{"security job", "security:"},
		{"code job", "code:"},
		{"test job", "test:"},
		{"needs bootstrap", "needs: [bootstrap]"},
		{"cidx run security", "run: ./bin/cidx run security"},
		{"cidx run code", "run: ./bin/cidx run code"},
		{"cidx run test", "run: ./bin/cidx run test"},
	}

	for _, check := range checks {
		if !strings.Contains(output, check.expected) {
			t.Errorf("%s: expected %q in output", check.name, check.expected)
		}
	}
}

func TestGitHub_PRPipeline(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"pr": {Phases: []string{"security", "code", "test"}},
		},
	}

	output, err := GitHub(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if !strings.Contains(output, "pull_request:") {
		t.Error("expected pull_request trigger for 'pr' pipeline")
	}
}

func TestGitHub_ReleasePipeline(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"release": {Phases: []string{"security", "code", "test", "build", "docker", "release"}},
		},
	}

	output, err := GitHub(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if !strings.Contains(output, "tags:") {
		t.Error("expected tags trigger for 'release' pipeline")
	}

	// All 6 phases should have jobs
	for _, phase := range []string{"security", "code", "test", "build", "docker", "release"} {
		if !strings.Contains(output, "run: ./bin/cidx run "+phase) {
			t.Errorf("expected job for phase %q", phase)
		}
	}
}

func TestGitHub_MultiplePipelines(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"pr":   {Phases: []string{"security", "code", "test"}},
			"main": {Phases: []string{"security", "code", "test", "build"}},
		},
	}

	output, err := GitHub(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Both triggers
	if !strings.Contains(output, "push:") {
		t.Error("expected push trigger")
	}
	if !strings.Contains(output, "pull_request:") {
		t.Error("expected pull_request trigger")
	}

	// build phase appears (from main) even though pr doesn't have it
	if !strings.Contains(output, "run: ./bin/cidx run build") {
		t.Error("expected build job from main pipeline")
	}
}

func TestGitHub_PhasesDeduplication(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"pr":   {Phases: []string{"security", "code", "test"}},
			"main": {Phases: []string{"security", "code", "test", "build"}},
		},
	}

	output, err := GitHub(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// security should appear exactly once as a job
	count := strings.Count(output, "run: ./bin/cidx run security")
	if count != 1 {
		t.Errorf("expected security phase once, found %d times", count)
	}
}

func TestCollectPhases_Order(t *testing.T) {
	pipelines := map[string]config.Pipeline{
		"pr":   {Phases: []string{"security", "code", "test"}},
		"main": {Phases: []string{"security", "code", "test", "build"}},
	}

	phases := collectPhases(pipelines)

	expected := []string{"security", "code", "test", "build"}
	if len(phases) != len(expected) {
		t.Fatalf("expected %d phases, got %d: %v", len(expected), len(phases), phases)
	}

	for i, phase := range expected {
		if phases[i] != phase {
			t.Errorf("phase[%d] = %q, want %q", i, phases[i], phase)
		}
	}
}

func TestGitHub_FetchDepth(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"ci": {Phases: []string{"security", "test"}},
		},
	}

	output, err := GitHub(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Security needs full history (for gitleaks), test doesn't
	// Just verify the output is valid and contains fetch-depth somewhere
	if !strings.Contains(output, "fetch-depth: 0") {
		t.Error("expected fetch-depth: 0 for security phase")
	}
}
