package generate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/cidx-org/cidx/pkg/config"
)

func TestGitHub_NoPipelines(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{},
	}

	_, err := GitHub(cfg)
	if err == nil {
		t.Error("expected error for empty pipelines")
	}
	if !strings.Contains(err.Error(), "no pipelines") {
		t.Errorf("expected 'no pipelines' error, got: %v", err)
	}
}

func TestGitHub_BasicCI(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"ci": {Phases: []string{"security", "code", "test"}},
		},
	}

	output, err := GitHub(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Check structure
	checks := []struct {
		name     string
		expected string
	}{
		{"header", "Generated by cidx"},
		{"name", "name: CIDX CI"},
		{"push trigger", "push:"},
		{"bootstrap job", "bootstrap:"},
		{"security job", "security:"},
		{"code job", "code:"},
		{"test job", "test:"},
		{"needs bootstrap", "needs: [bootstrap]"},
		{"cidx run security", "run: ./bin/cidx run security"},
		{"cidx run code", "run: ./bin/cidx run code"},
		{"cidx run test", "run: ./bin/cidx run test"},
	}

	for _, check := range checks {
		if !strings.Contains(output, check.expected) {
			t.Errorf("%s: expected %q in output", check.name, check.expected)
		}
	}
}

func TestGitHub_PRPipeline(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"pr": {Phases: []string{"security", "code", "test"}},
		},
	}

	output, err := GitHub(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if !strings.Contains(output, "pull_request:") {
		t.Error("expected pull_request trigger for 'pr' pipeline")
	}
}

func TestGitHub_ReleasePipeline(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"release": {Phases: []string{"security", "code", "test", "build", "docker", "release"}},
		},
	}

	output, err := GitHub(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if !strings.Contains(output, "tags:") {
		t.Error("expected tags trigger for 'release' pipeline")
	}

	// All 6 phases should have jobs
	for _, phase := range []string{"security", "code", "test", "build", "docker", "release"} {
		if !strings.Contains(output, "run: ./bin/cidx run "+phase) {
			t.Errorf("expected job for phase %q", phase)
		}
	}
}

func TestGitHub_MultiplePipelines(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"pr":   {Phases: []string{"security", "code", "test"}},
			"main": {Phases: []string{"security", "code", "test", "build"}},
		},
	}

	output, err := GitHub(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Both triggers
	if !strings.Contains(output, "push:") {
		t.Error("expected push trigger")
	}
	if !strings.Contains(output, "pull_request:") {
		t.Error("expected pull_request trigger")
	}

	// build phase appears (from main) even though pr doesn't have it
	if !strings.Contains(output, "run: ./bin/cidx run build") {
		t.Error("expected build job from main pipeline")
	}
}

func TestGitHub_PhasesDeduplication(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"pr":   {Phases: []string{"security", "code", "test"}},
			"main": {Phases: []string{"security", "code", "test", "build"}},
		},
	}

	output, err := GitHub(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// security should appear exactly once as a job
	count := strings.Count(output, "run: ./bin/cidx run security")
	if count != 1 {
		t.Errorf("expected security phase once, found %d times", count)
	}
}

func TestCollectPhases_Order(t *testing.T) {
	pipelines := map[string]config.Pipeline{
		"pr":   {Phases: []string{"security", "code", "test"}},
		"main": {Phases: []string{"security", "code", "test", "build"}},
	}

	phases := collectPhases(pipelines)

	expected := []string{"security", "code", "test", "build"}
	if len(phases) != len(expected) {
		t.Fatalf("expected %d phases, got %d: %v", len(expected), len(phases), phases)
	}

	for i, phase := range expected {
		if phases[i] != phase {
			t.Errorf("phase[%d] = %q, want %q", i, phases[i], phase)
		}
	}
}

func TestGitHub_FetchDepth(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"ci": {Phases: []string{"security", "test"}},
		},
	}

	output, err := GitHub(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Security needs full history (for gitleaks), test doesn't
	// Just verify the output is valid and contains fetch-depth somewhere
	if !strings.Contains(output, "fetch-depth: 0") {
		t.Error("expected fetch-depth: 0 for security phase")
	}
}

// TestGitHub_DefaultIsExternal locks in the contract that the bare GitHub(cfg)
// entrypoint emits the external-project bootstrap (`go install`), not the
// cidx-repo bootstrap (`go build`). This is the safe default for the broad
// audience: every project that runs `cidx generate github` from outside the
// cidx repo gets a workflow that bootstraps without source-tree assumptions
// (regression for cidx-org/cidx#124).
func TestGitHub_DefaultIsExternal(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"ci": {Phases: []string{"test"}},
		},
	}

	output, err := GitHub(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if !strings.Contains(output, "go install github.com/cidx-org/cidx/cmd/cidx@latest") {
		t.Error("default bootstrap should use `go install`, got:\n" + output)
	}
	if strings.Contains(output, "go build -o bin/cidx ./cmd/cidx") {
		t.Error("default bootstrap must not assume cmd/cidx/ source tree:\n" + output)
	}
	if !strings.Contains(output, "Install CIDX") {
		t.Error("expected step name 'Install CIDX' for external bootstrap")
	}
	// The downstream artifact contract (bin/cidx) must hold across both modes
	// so phase jobs don't have to branch on bootstrap mode.
	if !strings.Contains(output, "path: bin/cidx") {
		t.Error("artifact upload path bin/cidx must be preserved")
	}
}

// TestGitHubWithOptions_SelfBuild verifies the cidx-repo dogfood path: when
// SelfBuild is true the bootstrap builds from local source. This keeps cidx's
// own CI testing the binary it just changed, which is the only reason to keep
// the build path at all.
func TestGitHubWithOptions_SelfBuild(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"ci": {Phases: []string{"test"}},
		},
	}

	output, err := GitHubWithOptions(cfg, GitHubOptions{SelfBuild: true})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if !strings.Contains(output, "go build -o bin/cidx ./cmd/cidx") {
		t.Error("self-build bootstrap should use `go build`, got:\n" + output)
	}
	if strings.Contains(output, "go install") {
		t.Error("self-build bootstrap must not contain `go install`:\n" + output)
	}
	if !strings.Contains(output, "Build CIDX") {
		t.Error("expected step name 'Build CIDX' for self-build bootstrap")
	}
}

// TestGitHubWithOptions_External is the explicit-options counterpart to
// TestGitHub_DefaultIsExternal: the zero-value GitHubOptions must produce the
// same output as the legacy GitHub(cfg) entrypoint.
func TestGitHubWithOptions_External(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"ci": {Phases: []string{"test"}},
		},
	}

	withOpts, err := GitHubWithOptions(cfg, GitHubOptions{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	plain, err := GitHub(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if withOpts != plain {
		t.Errorf("GitHub(cfg) and GitHubWithOptions(cfg, GitHubOptions{}) must match\nplain:\n%s\nopts:\n%s", plain, withOpts)
	}
}

// TestIsCidxRepo verifies the auto-detection used by the CLI to pick the
// bootstrap mode. Two prongs (cmd/cidx/main.go AND go.mod module path) prevent
// false positives from any unrelated project that happens to have a cmd/cidx
// directory.
func TestIsCidxRepo(t *testing.T) {
	tests := []struct {
		name  string
		setup func(t *testing.T, dir string)
		want  bool
	}{
		{
			name: "cidx repo (both markers)",
			setup: func(t *testing.T, dir string) {
				t.Helper()
				cmdDir := filepath.Join(dir, "cmd", "cidx")
				if err := os.MkdirAll(cmdDir, 0755); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(filepath.Join(cmdDir, "main.go"), []byte("package main\n"), 0644); err != nil {
					t.Fatal(err)
				}
				gomod := "module github.com/cidx-org/cidx\n\ngo 1.23\n"
				if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(gomod), 0644); err != nil {
					t.Fatal(err)
				}
			},
			want: true,
		},
		{
			name: "external project — no cmd/cidx",
			setup: func(t *testing.T, dir string) {
				t.Helper()
				gomod := "module example.com/external\n\ngo 1.23\n"
				if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(gomod), 0644); err != nil {
					t.Fatal(err)
				}
			},
			want: false,
		},
		{
			name: "false positive guard — cmd/cidx/main.go but different module",
			setup: func(t *testing.T, dir string) {
				t.Helper()
				cmdDir := filepath.Join(dir, "cmd", "cidx")
				if err := os.MkdirAll(cmdDir, 0755); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(filepath.Join(cmdDir, "main.go"), []byte("package main\n"), 0644); err != nil {
					t.Fatal(err)
				}
				gomod := "module example.com/something/cmd/cidx\n\ngo 1.23\n"
				if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(gomod), 0644); err != nil {
					t.Fatal(err)
				}
			},
			want: false,
		},
		{
			name: "missing go.mod",
			setup: func(t *testing.T, dir string) {
				t.Helper()
				cmdDir := filepath.Join(dir, "cmd", "cidx")
				if err := os.MkdirAll(cmdDir, 0755); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(filepath.Join(cmdDir, "main.go"), []byte("package main\n"), 0644); err != nil {
					t.Fatal(err)
				}
			},
			want: false,
		},
		{
			name:  "empty dir",
			setup: func(t *testing.T, dir string) { t.Helper() },
			want:  false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			tt.setup(t, dir)
			if got := IsCidxRepo(dir); got != tt.want {
				t.Errorf("IsCidxRepo(%q) = %v, want %v", dir, got, tt.want)
			}
		})
	}
}

// TestGitHub_NoDeprecatedActionVersions asserts the generator does not emit
// action versions that GitHub has flagged as deprecated. Major versions v4
// and v5 of checkout / setup-go / upload-artifact / download-artifact run
// on Node.js 20, which GitHub forces off June 2, 2026 and removes
// September 16, 2026.
//
// Bumping cidx's own .github/workflows/ is not enough — the template that
// downstream projects regenerate via `cidx generate github` must also stay
// current, or every downstream CI emits deprecation annotations on each run.
//
// When GitHub announces another deprecation cycle, add the affected major
// versions to `deprecated`.
func TestGitHub_NoDeprecatedActionVersions(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"ci": {Phases: []string{"security", "code", "test", "build"}},
		},
	}

	output, err := GitHub(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	deprecated := []string{"@v4", "@v5"}
	actions := []string{
		"actions/checkout",
		"actions/setup-go",
		"actions/upload-artifact",
		"actions/download-artifact",
	}

	for _, action := range actions {
		for _, ver := range deprecated {
			needle := action + ver
			if strings.Contains(output, needle) {
				t.Errorf("generated workflow pins %q — Node 20 deprecated, forced off June 2, 2026", needle)
			}
		}
	}
}
