// Package generate produces CI platform configuration from cidx.toml.
package generate

import (
	"fmt"
	"strings"

	"github.com/cidx-org/cidx/pkg/config"
)

// GitHub generates a GitHub Actions workflow YAML from the CIDX config.
func GitHub(cfg *config.Config) (string, error) {
	if len(cfg.Pipelines) == 0 {
		return "", fmt.Errorf("no pipelines defined in cidx.toml")
	}

	var b strings.Builder

	b.WriteString("# Generated by cidx generate github\n")
	b.WriteString("# Source of truth: cidx.toml\n")
	b.WriteString("#\n")
	b.WriteString("# Regenerate with: cidx generate github -o .github/workflows/cidx.yml\n\n")

	// Build trigger section from pipeline names
	b.WriteString("name: CIDX CI\n\n")
	writeTriggers(&b, cfg.Pipelines)

	b.WriteString("\njobs:\n")

	// Bootstrap job -- build once, share binary
	writeBootstrapJob(&b)

	// Determine which phases appear across all pipelines
	phases := collectPhases(cfg.Pipelines)

	// One job per phase, all depending on bootstrap
	for _, phase := range phases {
		writePhaseJob(&b, phase)
	}

	return b.String(), nil
}

// writeTriggers generates the `on:` section based on pipeline names.
func writeTriggers(b *strings.Builder, pipelines map[string]config.Pipeline) {
	hasPR := false
	hasPush := false
	hasTag := false

	for name := range pipelines {
		switch name {
		case "pr":
			hasPR = true
		case "main", "ci":
			hasPush = true
		case "release":
			hasTag = true
		}
	}

	b.WriteString("on:\n")

	if hasPush {
		b.WriteString("  push:\n")
		b.WriteString("    branches: [main]\n")
		if hasTag {
			b.WriteString("    tags: [\"v*\"]\n")
		}
	}

	if hasPR {
		b.WriteString("  pull_request:\n")
		b.WriteString("    branches: [main]\n")
	}

	// If only release (tag) and no push
	if hasTag && !hasPush {
		b.WriteString("  push:\n")
		b.WriteString("    tags: [\"v*\"]\n")
	}
}

// writeBootstrapJob writes the bootstrap job that builds the CIDX binary.
func writeBootstrapJob(b *strings.Builder) {
	b.WriteString("  bootstrap:\n")
	b.WriteString("    name: Bootstrap\n")
	b.WriteString("    runs-on: ubuntu-latest\n")
	b.WriteString("    steps:\n")
	b.WriteString("      - uses: actions/checkout@v4\n")
	b.WriteString("        with:\n")
	b.WriteString("          fetch-depth: 0\n")
	b.WriteString("      - uses: actions/setup-go@v5\n")
	b.WriteString("        with:\n")
	b.WriteString("          go-version: \"1.23\"\n")
	b.WriteString("          cache: true\n")
	b.WriteString("      - name: Build CIDX\n")
	b.WriteString("        run: go build -o bin/cidx ./cmd/cidx\n")
	b.WriteString("      - uses: actions/upload-artifact@v4\n")
	b.WriteString("        with:\n")
	b.WriteString("          name: cidx-binary\n")
	b.WriteString("          path: bin/cidx\n")
	b.WriteString("          retention-days: 1\n\n")
}

// writePhaseJob writes a single phase job that downloads the binary and runs the phase.
func writePhaseJob(b *strings.Builder, phase string) {
	// Capitalize first letter for display name
	displayName := strings.ToUpper(phase[:1]) + phase[1:]

	fmt.Fprintf(b, "  %s:\n", phase)
	fmt.Fprintf(b, "    name: %s\n", displayName)
	b.WriteString("    runs-on: ubuntu-latest\n")
	b.WriteString("    needs: [bootstrap]\n")
	b.WriteString("    steps:\n")
	b.WriteString("      - uses: actions/checkout@v4\n")

	// Some phases need full history
	if phase == "security" || phase == "code" {
		b.WriteString("        with:\n")
		b.WriteString("          fetch-depth: 0\n")
	}

	b.WriteString("      - uses: actions/download-artifact@v4\n")
	b.WriteString("        with:\n")
	b.WriteString("          name: cidx-binary\n")
	b.WriteString("          path: bin\n")
	b.WriteString("      - run: chmod +x bin/cidx\n")
	fmt.Fprintf(b, "      - name: Run %s\n", phase)
	fmt.Fprintf(b, "        run: ./bin/cidx run %s\n\n", phase)
}

// collectPhases returns deduplicated phases in order of first appearance.
func collectPhases(pipelines map[string]config.Pipeline) []string {
	seen := make(map[string]bool)
	var phases []string

	// Process pipelines in a deterministic order
	for _, name := range []string{"pr", "ci", "main", "release"} {
		p, ok := pipelines[name]
		if !ok {
			continue
		}
		for _, phase := range p.Phases {
			if !seen[phase] {
				seen[phase] = true
				phases = append(phases, phase)
			}
		}
	}

	// Catch any custom pipeline names not in the standard list
	for _, p := range pipelines {
		for _, phase := range p.Phases {
			if !seen[phase] {
				seen[phase] = true
				phases = append(phases, phase)
			}
		}
	}

	return phases
}
