package generate

import (
	"fmt"
	"strings"

	"github.com/cidx-org/cidx/pkg/config"
)

// GitLab generates a GitLab CI configuration YAML from the CIDX config.
func GitLab(cfg *config.Config) (string, error) {
	if len(cfg.Pipelines) == 0 {
		return "", fmt.Errorf("no pipelines defined in cidx.toml")
	}

	var b strings.Builder

	b.WriteString("# Generated by cidx generate gitlab\n")
	b.WriteString("# Source of truth: cidx.toml\n")
	b.WriteString("#\n")
	b.WriteString("# Regenerate with: cidx generate gitlab -o .gitlab-ci.yml\n\n")

	// Stages from collected phases
	phases := collectPhases(cfg.Pipelines)

	b.WriteString("stages:\n")
	b.WriteString("  - bootstrap\n")
	for _, phase := range phases {
		fmt.Fprintf(&b, "  - %s\n", phase)
	}
	b.WriteString("\n")

	// Variables
	b.WriteString("variables:\n")
	b.WriteString("  CIDX_BINARY: bin/cidx\n\n")

	// Bootstrap job
	writeGitLabBootstrap(&b)

	// Phase jobs
	for _, phase := range phases {
		writeGitLabPhaseJob(&b, phase, cfg.Pipelines)
	}

	return b.String(), nil
}

// writeGitLabBootstrap writes the bootstrap job that builds CIDX.
func writeGitLabBootstrap(b *strings.Builder) {
	b.WriteString("bootstrap:\n")
	b.WriteString("  stage: bootstrap\n")
	b.WriteString("  image: golang:1.23-alpine\n")
	b.WriteString("  script:\n")
	b.WriteString("    - go build -o bin/cidx ./cmd/cidx\n")
	b.WriteString("  artifacts:\n")
	b.WriteString("    paths:\n")
	b.WriteString("      - bin/cidx\n")
	b.WriteString("    expire_in: 1 hour\n\n")
}

// writeGitLabPhaseJob writes a single phase job.
func writeGitLabPhaseJob(b *strings.Builder, phase string, pipelines map[string]config.Pipeline) {
	displayName := strings.ToUpper(phase[:1]) + phase[1:]

	fmt.Fprintf(b, "%s:\n", phase)
	fmt.Fprintf(b, "  stage: %s\n", phase)
	b.WriteString("  image: docker:latest\n")
	b.WriteString("  services:\n")
	b.WriteString("    - docker:dind\n")
	b.WriteString("  needs:\n")
	b.WriteString("    - bootstrap\n")
	b.WriteString("  script:\n")
	b.WriteString("    - chmod +x bin/cidx\n")
	fmt.Fprintf(b, "    - ./bin/cidx run %s\n", phase)

	// Build rules from pipeline names that include this phase
	rules := gitlabRulesForPhase(phase, pipelines)
	if len(rules) > 0 {
		b.WriteString("  rules:\n")
		for _, rule := range rules {
			fmt.Fprintf(b, "    - %s\n", rule)
		}
	}

	fmt.Fprintf(b, "  # %s phase\n\n", displayName)
}

// gitlabRulesForPhase determines which GitLab CI rules apply for a phase.
func gitlabRulesForPhase(phase string, pipelines map[string]config.Pipeline) []string {
	var rules []string
	seen := make(map[string]bool)

	for name, pipeline := range pipelines {
		if !pipelineHasPhase(pipeline, phase) {
			continue
		}

		var rule string
		switch name {
		case "pr":
			rule = "if: $CI_MERGE_REQUEST_ID"
		case "main", "ci":
			rule = "if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
		case "release":
			rule = "if: $CI_COMMIT_TAG"
		default:
			continue
		}

		if !seen[rule] {
			seen[rule] = true
			rules = append(rules, rule)
		}
	}

	return rules
}

// pipelineHasPhase checks if a pipeline includes a specific phase.
func pipelineHasPhase(pipeline config.Pipeline, phase string) bool {
	for _, p := range pipeline.Phases {
		if p == phase {
			return true
		}
	}
	return false
}
