package generate

import (
	"strings"
	"testing"

	"github.com/cidx-org/cidx/pkg/config"
)

func TestGitLab_NoPipelines(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{},
	}

	_, err := GitLab(cfg)
	if err == nil {
		t.Error("expected error for empty pipelines")
	}
}

func TestGitLab_BasicCI(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"ci": {Phases: []string{"security", "code", "test"}},
		},
	}

	output, err := GitLab(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	checks := []struct {
		name     string
		expected string
	}{
		{"header", "Generated by cidx"},
		{"stages", "stages:"},
		{"bootstrap stage", "- bootstrap"},
		{"security stage", "- security"},
		{"bootstrap job", "bootstrap:"},
		{"golang image", "golang:1.23-alpine"},
		{"dind service", "docker:dind"},
		{"needs bootstrap", "- bootstrap"},
		{"cidx run security", "./bin/cidx run security"},
		{"cidx run code", "./bin/cidx run code"},
		{"cidx run test", "./bin/cidx run test"},
	}

	for _, check := range checks {
		if !strings.Contains(output, check.expected) {
			t.Errorf("%s: expected %q in output", check.name, check.expected)
		}
	}
}

func TestGitLab_PRPipeline(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"pr": {Phases: []string{"security", "code", "test"}},
		},
	}

	output, err := GitLab(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if !strings.Contains(output, "CI_MERGE_REQUEST_ID") {
		t.Error("expected merge request rule for 'pr' pipeline")
	}
}

func TestGitLab_ReleasePipeline(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"release": {Phases: []string{"security", "build", "release"}},
		},
	}

	output, err := GitLab(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if !strings.Contains(output, "CI_COMMIT_TAG") {
		t.Error("expected tag rule for 'release' pipeline")
	}
}

func TestGitLab_MultiplePipelines(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"pr":   {Phases: []string{"security", "code", "test"}},
			"main": {Phases: []string{"security", "code", "test", "build"}},
		},
	}

	output, err := GitLab(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if !strings.Contains(output, "CI_MERGE_REQUEST_ID") {
		t.Error("expected merge request rule")
	}
	if !strings.Contains(output, "CI_DEFAULT_BRANCH") {
		t.Error("expected default branch rule")
	}
	if !strings.Contains(output, "./bin/cidx run build") {
		t.Error("expected build job")
	}
}

func TestGitLab_PhasesDeduplication(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"pr":   {Phases: []string{"security", "code", "test"}},
			"main": {Phases: []string{"security", "code", "test", "build"}},
		},
	}

	output, err := GitLab(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	count := strings.Count(output, "./bin/cidx run security")
	if count != 1 {
		t.Errorf("expected security phase once, found %d times", count)
	}
}

func TestGitLab_Artifacts(t *testing.T) {
	cfg := &config.Config{
		Pipelines: map[string]config.Pipeline{
			"ci": {Phases: []string{"test"}},
		},
	}

	output, err := GitLab(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if !strings.Contains(output, "artifacts:") {
		t.Error("expected artifacts section for bootstrap")
	}
	if !strings.Contains(output, "expire_in:") {
		t.Error("expected expire_in for artifacts")
	}
}
